version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    # container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  php:
    image: wodby/drupal-php:7.1-2.1.0
    # container_name: "${PROJECT_NAME}_php"
    depends_on:
      - mariadb
    # environment:
    #   PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    #   DB_HOST: $DB_HOST
    #   DB_USER: $DB_USER
    #   DB_PASSWORD: $DB_PASSWORD
    #   DB_NAME: $DB_NAME
    #   DB_DRIVER: $DB_DRIVER
    #   COLUMNS: 80 # Set 80 columns for docker exec -it.
## Read instructions at https://wodby.com/stacks/drupal/docs/local/xdebug/
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ & Linux/Mac/Win
#      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux, Docker < 18.03
#      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS, Docker < 18.03
#      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows, Docker < 18.03
    volumes:
      - ./:/var/www/html

  nginx:
    image:  wodby/apache:2.4-4.0.0
    # container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    ports:
      - '8080:80'
    environment:
#      NGINX_PAGESPEED: "on"
      APACHE_VHOST_PRESET: php
      APACHE_DIRECTORY_INDEX: index.php
      APACHE_BACKEND_HOST: php
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
      # NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
#      NGINX_DRUPAL_FILE_PROXY_URL: http://example.com
    volumes_from:
      - php
    volumes:
      - ./:/var/www/html